export const COPY = {
  actionTitle: "Annotations",
  selectHint: "Selecione um elemento",
  cancel: "Cancelar",
  capture: "Enviar ao T3",
  debug: "Debug",
  debugMode: "Modo debug",
  hudTitle: "Annotations",
  pick: "Pick",
  closeOverlay: "Fechar overlay",
  commentLabel: "Comentário",
  commentPlaceholder: "O que você quer mudar aqui?",
  emptyComment: "Escreva um comentário antes de capturar.",
  copying: "Enviando...",
  bridgeChecking: "T3 verificando...",
  bridgeConnected: "T3 conectado",
  bridgeNoComposer: "T3 sem Composer ativo",
  bridgeUnavailable: "T3 não alcançável",
  sentToT3: "Imagem salva e nota enviada ao T3.",
  t3FallbackCopied: "T3 indisponível; nota copiada.",
  t3FallbackWillCopy: "T3 indisponível; vou copiar a nota.",
  t3NoComposerCopied: "T3 sem Composer ativo; nota copiada.",
  t3NoComposerWillCopy: "T3 sem Composer ativo; vou copiar a nota.",
  t3UnreachableCopied: "T3 não alcançável; nota copiada.",
  t3UnreachableWillCopy: "T3 não alcançável; vou copiar a nota.",
  t3AckTimeoutCopied: "T3 não confirmou; nota copiada.",
  copied: "Imagem salva e nota copiada.",
  captureFailed: "Não foi possível concluir.",
  fallbackTitle: "Nota não copiada",
  fallbackManual:
    "A imagem foi salva, mas o Chrome bloqueou a cópia da nota. Copie o texto abaixo manualmente.",
  restrictedPage: "Página restrita para extensões Chrome.",
  reselect: "Voltar para seleção",
} as const;

export const SHORTCUTS = {
  toggleOverlay: "Alt+A",
  submit: "Cmd+Enter",
  submitAlt: "Ctrl+Enter",
  cancel: "Esc",
  reselect: "Backspace",
} as const;
